clone_folder: C:\Matazure\tensor

# do not build on tags
skip_tags: true

# clone only the top level commit
shallow_clone: false

branches:
  only:
    - master
    - dev

# environment variables
environment:
  global:
    INTELOCLSDKROOT: C:\Program Files (x86)\Intel\OpenCL SDK\
    BOOST_COMPUTE_DEFAULT_PLATFORM: Intel(R) OpenCL
  matrix:
     - VS_VER: 2015
       BOOST_ROOT: C:\Libraries\boost_1_59_0
       BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

image: Visual Studio 2015

# build platforms
platform:
  - x64

configuration:
  - Release

# before_build:
#   - appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/8539/intel_sdk_for_opencl_setup_6.0.0.1049.exe"
  # - start /wait .\intel_sdk_for_opencl_setup_6.0.0.1049.exe install --output=output.log --eula=accept
  # #- type output.log
  # - appveyor DownloadFile "http://registrationcenter-download.intel.com/akdlm/irc_nas/9022/opencl_runtime_16.1.1_x64_setup.msi"
  # - start /wait msiexec /i opencl_runtime_16.1.1_x64_setup.msi /qn  /l*v msiexec2.log
  # #- type msiexec2.log

install:

build_script:
  - ./script/build_win.bat

# test_script:
#   - cd build_win
